Kendall
WonderTix/WonderTix pull request #114
Opened 2022-10-13 19:19 UTC by KENDARRR

## Brief Description

Discount code API added. GET, DELETE, and POST are routes are active once the new db gets merged. Delete simply changes the number us uses left to 0 so no one else can the coupon code. The others work as expected.

## References Issue

Issue 103

## Type of change

- [ ] Bug fix
- [!!!] Feature
- [ ] Major change (potentially breaking, list anything that is broken below)
- [ ] Documentation

### Breaking Changes

Incompatible with current db. Will work once the new db is merged
## Testing done

Describe tests that were used, along with instructions for testing.

- [ !] Postman GET route
- [ !] Postman DELETE route
- [ !] Postman POST route

- [ !] Docker was used.
- [ ] Docker was not used and I have listed my configuration below.

**System Specifications**:
* Operating System: Win 11 Home
* Node Version: 16.16.0
* NPM Version: 8.18.0

## Checklist:

- [! ] My code follows the styling guidelines.
- [ !] I have added unit tests and verified that they pass.
- [ ] I have used the linter and fixed any linting issues.
- [! ] I have commented the code.
- [ !] I have adjusted the documentation to match the changed code.
- [! ] Prior to submitting the PR, I made sure the latest changes were merged with my branch.
- [ !] Existing tests pass locally with changes.

### Explanation for unchecked

I'm checking with Ben about Linting right now

2022-10-14 18:39 UTC, ben16williams requested changes
Nice job with documentation

2022-10-14 18:39 UTC, ben16williams commented on server/src/api/discounts/discounts.router.ts
> +discountsRouter.post('/', async(
This should probably be a private route

2022-10-14 18:39 UTC, ben16williams commented on server/src/api/discounts/discounts.router.ts
> +discountsRouter.delete('/:id', async(
This should also probably be private

2022-10-14 18:39 UTC, ben16williams commented on server/src/api/discounts/discounts.router.ts
> +//discountsRouter.use(checkScopes);
Do we need these as comments here?

2022-10-15 01:30 UTC, ben16williams commented
Can you also make the title of the PR something that shortly describes the work?

2022-10-18 04:14 UTC, KENDARRR commented on server/src/api/discounts/discounts.router.ts
> +//discountsRouter.use(checkScopes);
All should be fixed now

2022-10-20 07:22 UTC, ben16williams approved these changes

2022-10-21 01:24 UTC, merged